AWSTemplateFormatVersion: 2010-09-09
Description: Devops Hometask Aws Environment
Parameters:
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  MainInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MainVPS
      InternetGatewayId: !Ref MainInternetGateway
  MainRoute:
    Type: 'AWS::EC2::Route'
    DependsOn:
      - MainInternetGateway
      - AttachGateway
    Properties:
      RouteTableId:
        Ref: MainRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MainInternetGateway
  MainRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: MainVPS
  MainVPS:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 192.168.67.0/24
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
        - Key: name
          Value: main-vps
  FirstSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: MainVPS
      CidrBlock: 192.168.67.0/25
      AvailabilityZone: eu-north-1a
  SecondSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: MainVPS
      CidrBlock: 192.168.67.128/25
      AvailabilityZone: eu-north-1b
  FirstWebServer:
    Type: 'AWS::EC2::Instance'
#    CreationPolicy:
#      ResourceSignal:
#        Timeout: PT15M
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          InstallAndRun:
            - Install
            - ServiceStart
        Install:
          commands:
            01_command:
              command: |
                sudo yum update -y
            02_command:
              command: |
                sudo yum install aws-cfn-bootstrap -y
            03_command:
              command: |
                sudo amazon-linux-extras install nginx1 -y
        ServiceStart:
          services:
            sysvinit:
              nginx:
                enabled: 'true'
                ensureRunning: 'true'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: "t3.micro"
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - Ref: WebServerSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref FirstSubnet
#      SecurityGroups:
#        - !Ref WebServerSecurityGroup
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -x
            - |
              # Install the files and packages from the metadata
            - |
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource FirstWebServer '
            - '         --configsets InstallAndRun '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

            - |
              # Signal the status from cfn-init
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource FirstWebServer '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

  SecondWebServer:
    Type: 'AWS::EC2::Instance'
#    CreationPolicy:
#      ResourceSignal:
#        Timeout: PT15M
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          InstallAndRun:
            - Install
            - ServiceStart
        Install:
          commands:
            01_command:
              command: |
                sudo yum update -y
            02_command:
              command: |
                sudo yum install aws-cfn-bootstrap -y
            03_command:
              command: |
                sudo amazon-linux-extras install nginx1 -y
        ServiceStart:
          services:
            sysvinit:
              nginx:
                enabled: 'true'
                ensureRunning: 'true'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: "t3.micro"
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - Ref: WebServerSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref SecondSubnet
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -x
            - |
              # Install the files and packages from the metadata
            - |
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource SecondWebServer '
            - '         --configsets InstallAndRun '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

            - |
              # Signal the status from cfn-init
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource SecondWebServer '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref MainVPS
      GroupDescription: Security group from hometask for devops course
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
        - CidrIp: 0.0.0.0/0
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
  MyListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MainLoadBalancer
      Port: 80
      Protocol: "HTTP"
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPort: 80
      HealthCheckPath: /
#      Matcher: 200
      Protocol: HTTP
      Port: 80
      Name: MyTargets
      TargetType: instance
      VpcId: !Ref MainVPS
      Targets:
      - Id: !Ref FirstWebServer
      - Id: !Ref SecondWebServer
  MainLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      Subnets:
        - !Ref FirstSubnet
        - !Ref SecondSubnet
Outputs:
  PublicIpFirstServer:
    Description: EC2 public IP
    Value: !GetAtt FirstWebServer.PublicIp
#  PublicIpSecondServer:
#    Description: EC2 public IP
#    Value: !GetAtt SecondWebServer.PublicIp