- name: Ensure that nginx is installed
  yum: 
    pkg: nginx
    state: present

- name: Add the user 'nginx'
  user:
    name: nginx
    shell: /bin/false

- name: Set up permissions for log folder
  file:
    path: /var/log/nginx
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: u=rwx,g=rwx,o=r

- name: Set up permissions for lib folder
  file:
    path: /var/lib/nginx
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: u=rwx,g=rwx,o=r

- name: Replace old username with nginx user
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: 'user.+?;'
    replace: 'user nginx;'

- name: Populate an nginx config
  template: 
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site.conf
  notify: reload nginx

- name: Enable nginx service
  service: 
    name: nginx
    state: started
    enabled: yes