# - name: Enable amazon-linux-extras packages
#   shell: amazon-linux-extras enable epel
  
- name: Ensure that essential packages are installed
  yum: 
    name:
    - epel-release
    - git
    - pip
    - policycoreutils-python
    - java
    state: present

- name: Ensure that we have all python libraries
  pip: 
    name:
      - selinux

- import_tasks: selinux.yml
- import_tasks: nginx.yml