- name: Create the root folder
  file: 
    name: "{{ backend_app_root }}"
    state: directory

- name: Copy js file to server
  copy:
     src: "{{ artifact_name }}"
     dest: "{{ backend_app_root }}/novikov-backend-app.js"

- name: Populate an backend-app service config
  template: 
    src: novikov-backend-app.service.j2
    dest: /etc/systemd/system/novikov-backend-app.service
  # notify: reload novikov-backend-app

- name: Enable backend-app service
  service: 
    name: novikov-backend-app
    state: started
    enabled: yes